### ISSUE TITLE
Don't attempt to map properties that are commented out in YML files

### ISSUE THREAD

**Issue by binaryblake** [libertymutual/herman#69]
Currently Herman will attempt to parse template variables, even if they live within a comment in YML:
```
#    testVar: ${my.test.var}
```
This can cause some confusion/annoyance and isn't obvious what's going on.

**Comment by c1phr** [comment]
We've had this one around for a while. I think this will take some re-working of how the variable injecting works, since right now it just treats the yml as a blob of text rather than actually parsing it as proper yml.

**Comment by binaryblake** [comment]
Yep, probably not critical either, just wanted to make sure we have it logged. This is also YML specific since JSON doesnt allow comments at all.

**Comment by fritzdj** [comment]
I think this is an easy fix actually. Could we convert to yml, convert to string and do the variable replacement, convert to yml?

**Comment by binaryblake** [comment]
Yeah good call - if we convert everything to YML first, hopefully it should parse out any comments for us.
